x-service: &base
  build: .
  network_mode: host
  entrypoint: /ros_entrypoint.sh
  volumes:
    - ./cyclone_config.xml:/cyclone_config.xml:ro
    - ./motor_node.py:/ros_ws/motor_node.py
  environment:
    - RMW_IMPLEMENTATION=rmw_cyclonedds_cpp
    - CYCLONEDDS_URI=file:///cyclone_config.xml

services:
  foxglove_bridge:
    <<: *base
    command: ros2 run foxglove_bridge foxglove_bridge --ros-args -p send_buffer_limit:=500000

  motor_driver:
    <<: *base
    privileged: true
    command: python3 /ros_ws/motor_node.py

  camera:
    <<: *base
    privileged: true
    devices:
      - /dev/bus/usb:/dev/bus/usb
    command: ros2 launch realsense2_camera rs_launch.py rgb_camera.color_profile:=424x240x15 depth_module.depth_profile:=424x240x15 image_qos:=SENSOR_DATA enable_depth:=false
